# Generated by Django 3.1 on 2021-09-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuserrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserRole',
        ),
    ]
