# Generated by Django 3.1 on 2021-10-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_customuserrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['pk']},
        ),
    ]
