# Generated by Django 3.1 on 2021-09-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210904_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='part_of_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
