# Generated by Django 3.1 on 2021-09-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210909_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_active',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ACT', 'Активно'), ('CLS', 'Закрыто')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
